trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: 
  - stage: DevDeploy
  - stage: QADeploy
  - stage: ProdDeploy

steps:
- script: echo Job1 Step1
  displayName: 'Run a one-line script'

