trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: Job1
      steps:
      - bash: echo Build First Job 
      - bash: echo $(PipelineLevelVar)
      - bash: echo $(Build.BuildNumber)
      - bash: echo $(Build.BuildId)
      - bash: echo $(Build.SourceBranchName)
      - bash: echo $(Build.SourcesDirectory)
      - bash: echo $(System.DefaultWorkingDirectory)
      - bash: ls -R $(System.DefaultWorkingDirectory)
      - bash: echo $(Build.ArtifactStagingDirectory)
      - bash: java -version
      - bash: node --version
      - bash: python --version
      - bash: mvn -version
      - bash: ls -R $(Build.ArtifactStagingDirectory)
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: |
            **/*.yaml
            **/*.tf
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - bash: ls -R $(Build.ArtifactStagingDirectory)
    - job: Job2
      steps:
      - bash: echo Build Second Job 
  - stage: DevDeploy 
    dependsOn: Build
    variables:
      environment: Dev
    jobs:
    - job: DevDeployJob
      steps:
      - bash: echo Build $(environment)Deploy Job
  - stage: QADeploy
    dependsOn:
    - Build
    - DevDeploy
    variables:
      environment: QA
    jobs:
    - job: QADeployJob
      steps:
      - bash: echo Build $(environment)Deploy Job 
  - stage: ProdDeploy
    dependsOn:
    - QADeploy
    - DevDeploy
    jobs:
    - job: ProdDeployJob
      steps:
      - bash: echo Build ProdDeploy Job 


