trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: Job1
      steps:
      - bash: echo Build First Job 
    - job: Job2
      steps:
      - bash: echo Build Second Job 
  - stage: DevDeploy 
    dependsOn: Build
    jobs:
    - job: DevDeployJob
      steps:
      - bash: echo Build DevDeploy Job
  - stage: QADeploy
    dependsOn:
    - Build
    - DevDeploy
    jobs:
    - job: QADeployJob
      steps:
      - bash: echo Build QADeploy Job 
  - stage: ProdDeploy
    dependsOn:
    - QADeploy
    - DevDeploy
    jobs:
    - job: ProdDeployJob
      steps:
      - bash: echo Build ProdDeploy Job 


