trigger:
- main

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'

pool:
  # vmImage: $(operatingSystem)
  vmimage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
    - job: BuildJob
      steps:
      - bash: echo "Do the build"
        
- stage: Deployment
  jobs:
    - deployment: DeploymentDeploymentJob
      environment: Dev
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo deploy to Dev

- stage: QADeployment
  jobs:
    - deployment: QADeploymentDeploymentJob
      environment: QA
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo deploy to QA with an approver